#!/usr/bin/env bash

# 快速启动脚本 - 帮助您快速开始使用扩展

echo "======================================"
echo "   自动化采集工具 - 快速启动指南"
echo "======================================"
echo ""

echo "📚 项目文件结构："
echo "  ✓ manifest.json          - 扩展配置"
echo "  ✓ popup.html            - UI 界面"
echo "  ✓ popup.css             - 样式表"
echo "  ✓ popup.js              - 界面逻辑"
echo "  ✓ background.js         - 后台脚本"
echo "  ✓ content-script.js     - 页面脚本"
echo "  ✓ README.md             - 详细文档"
echo "  ✓ USAGE_EXAMPLES.md     - 使用示例"
echo ""

echo "🚀 安装步骤："
echo ""
echo "1️⃣  打开 Chrome 浏览器"
echo ""
echo "2️⃣  进入扩展管理页面"
echo "   • 输入 chrome://extensions/"
echo "   • 或点击菜单 → 更多工具 → 扩展程序"
echo ""
echo "3️⃣  启用开发者模式"
echo "   • 点击右上角的 【开发者模式】 开关"
echo ""
echo "4️⃣  加载此项目"
echo "   • 点击【加载已解压的扩展程序】"
echo "   • 选择项目文件夹："
echo "   • /Users/zhuyun/www/collect"
echo ""
echo "5️⃣  完成！"
echo "   • 扩展将出现在 Chrome 工具栏"
echo "   • 点击扩展图标打开配置面板"
echo ""

echo "💡 快速使用："
echo ""
echo "1. 输入 URL 和点击元素的 CSS 选择器"
echo "2. 设置页面加载延迟时间"
echo "3. 点击【➕ 添加链接】"
echo "4. 加完所有链接后，点击【▶️ 开始运行】"
echo ""

echo "📖 查看文档："
echo "   • README.md         - 完整功能说明"
echo "   • USAGE_EXAMPLES.md - 详细使用示例"
echo ""

echo "❓ 需要帮助？"
echo "   • 查看浏览器控制台（F12 → Console）中的日志"
echo "   • 查看扩展面板中的运行日志"
echo "   • 参考 USAGE_EXAMPLES.md 中的示例"
echo ""

echo "======================================"
echo "✨ 祝您使用愉快！"
echo "======================================"
